import "@/styles/globals.css";
import { Navbar, Footer } from "@/components";
export const metadata = {
  title: {
    default: "Belhana with Sameh Sedky",
    title: "%s | Belhana with Sameh Sedky",
  },
  description: "Generated by create next app",
};

export default function BelhanaLayout({ children }) {
  return (
    <>
      <Navbar />
      <main>{children}</main>
      <Footer />
    </>
  );
}
